### ISSUE TITLE
Stock on Computing directory structure...

### ISSUE THREAD

**Issue by Jungle666** [dpoluyanov/bazel-wsl#2]
Building Bazel targets...
build invocation result: success
Parsing build outputs...
Total rules: 0, new/changed: 0, removed: 0
Reading IDE info result...
Reading IDE info result...
Updating target map
Loaded 0 aspect files, total size 0kB
Target map size: 0
Prefetching output artifacts...
Command: "D:\Program Files\bazel\bazel-wsl.exe" info --tool_tag=ijwb:IDEA:ultimate build-language --curses=no --color=yes --progress_in_terminal_title=no --

INFO: Invocation ID: a0cf1fa8-a653-4dde-ae20-224459128a88
Reading jdeps files...
Loaded 0 jdeps files, total size 0kB
Reading package manifests...
Java content entry count: 1
Filtering empty jars...
Fetching JARs to track empty status..
Filtered 0 JARs, in 0ms
Updating Jar Cache...
Prefetching files...
Refreshing files
Computing directory structure...

com.google.repackaged.bazel.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
	at com.google.repackaged.bazel.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:106)
	at com.google.repackaged.bazel.protobuf.CodedInputStream$ArrayDecoder.checkLastTagWas(CodedInputStream.java:635)
	at com.google.repackaged.bazel.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
	at com.google.devtools.build.lib.query2.proto.proto2api.Build$BuildLanguage.<init>(Build.java:42300)
	at com.google.devtools.build.lib.query2.proto.proto2api.Build$BuildLanguage.<init>(Build.java:42250)
	at com.google.devtools.build.lib.query2.proto.proto2api.Build$BuildLanguage$1.parsePartialFrom(Build.java:43090)
	at com.google.devtools.build.lib.query2.proto.proto2api.Build$BuildLanguage$1.parsePartialFrom(Build.java:43084)
	at com.google.repackaged.bazel.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
	at com.google.repackaged.bazel.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
	at com.google.repackaged.bazel.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
	at com.google.repackaged.bazel.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
	at com.google.repackaged.bazel.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at com.google.devtools.build.lib.query2.proto.proto2api.Build$BuildLanguage.parseFrom(Build.java:42490)
	at com.google.idea.blaze.base.lang.buildfile.sync.BuildLangSyncPlugin.parseLanguageSpec(BuildLangSyncPlugin.java:124)
	at com.google.idea.blaze.base.lang.buildfile.sync.BuildLangSyncPlugin.lambda$getBuildLanguageSpec$0(BuildLangSyncPlugin.java:95)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:40)
	at com.google.idea.blaze.base.lang.buildfile.sync.BuildLangSyncPlugin.getBuildLanguageSpec(BuildLangSyncPlugin.java:90)
	at com.google.idea.blaze.base.lang.buildfile.sync.BuildLangSyncPlugin.updateSyncState(BuildLangSyncPlugin.java:71)
	at com.google.idea.blaze.base.sync.ProjectUpdateSyncTask.lambda$run$2(ProjectUpdateSyncTask.java:180)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:57)
	at com.google.idea.blaze.base.sync.ProjectUpdateSyncTask.run(ProjectUpdateSyncTask.java:175)
	at com.google.idea.blaze.base.sync.ProjectUpdateSyncTask.runProjectUpdatePhase(ProjectUpdateSyncTask.java:120)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$updateProjectAndFinishSync$7(SyncPhaseCoordinator.java:508)
	at com.google.idea.blaze.base.sync.SyncScope.lambda$runWithTiming$1(SyncScope.java:61)
	at com.google.idea.blaze.base.sync.SyncScope.lambda$push$2(SyncScope.java:74)
	at com.google.idea.blaze.base.sync.SyncScope.push(SyncScope.java:89)
	at com.google.idea.blaze.base.sync.SyncScope.push(SyncScope.java:71)
	at com.google.idea.blaze.base.sync.SyncScope.runWithTiming(SyncScope.java:63)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.updateProjectAndFinishSync(SyncPhaseCoordinator.java:500)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.runSync(SyncPhaseCoordinator.java:404)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$0(SyncPhaseCoordinator.java:229)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:57)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:33)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$1(SyncPhaseCoordinator.java:219)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:79)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$4(ProgressiveTaskWithProgressIndicator.java:127)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$5(ProgressiveTaskWithProgressIndicator.java:127)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Jungle666** [comment]
/mnt/c/Users/jungleliu$ bazel version
Bazelisk version: v1.11.0
Build label: 4.2.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 2 18:15:58 2021 (1638468958)
Build timestamp: 1638468958
Build timestamp as int: 1638468958

**Comment by dpoluyanov** [comment]
Thanks, I'll try to reproduce problem with version 4.2.2,
For clarification, did you checkout the project into directory inside in `/home/jungleliu/...` or somewhere else?

**Comment by Jungle666** [comment]
thanks，project directory in /home/jungleliu/git/*

**Comment by Jungle666** [comment]
4.2.1 works fine for me

**Comment by dpoluyanov** [comment]
I've found that exception is caused by occasionally patching `bazel info build-language` command, so I've created a small change https://github.com/dpoluyanov/bazel-wsl/commit/26f413878f97104fd44fb3e7026b2eab989817d8 in order to skip patching for build-language command, so you could build & try again with bazel version 4.2.2 if it fixes an issue or not

**Comment by dpoluyanov** [comment]
Just now, in https://github.com/dpoluyanov/bazel-wsl/releases/tag/v0.0.2 
It's build from macOS, so I couldn't test it now

**Comment by Jungle666** [comment]
> I rebuild with it myself just now,test for result.

**Comment by Jungle666** [comment]
Thanks very much.   There is no error after that.  I'm finding out other issues.
